---
- name: Converge
  hosts: all
  vars:
    # Ansible vars EXAMPLE!
    ansible_python_interpreter: /usr/bin/python3
    # Custom var, that used in include_tasks (zsh.yml)
    username: root

    dans_repos:
      file:
        - "yum.repos.d/dans-pacur.repo"
      copr:
        - "flatcap/neomutt"
      dnf:
        # yamllint disable rule:line-length
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"  # noqa 204
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"  # noqa 204
        - "https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-32-1.noarch.rpm"
        # yamllint enable rule:line-length


    dans_tools:
      # Need everything: deps, tasks, several configs
      - name: zsh
        desc: 'Interactive shell'
        deps: {'dnf':[fontconfig, util-linux-user, ruby, gawk, git, xclip, fzf]}
        include_tasks: zsh.yml
        config:
          - src: zsh
            dest: ~/.zshrc
          - src: zshalias
            dest: ~/.zshalias

      # Only configs
      - name: tmux
        desc: 'Terminal windows multiplexer'
        config:
          - src: tmux
            dest: ~/.tmux.conf

      # Three config files with root config
      - name: git                           # Version control system
        config:
          - src: gitconfig
            dest: ~/.gitconfig
          - src: gitexcludes
            dest: ~/.gitexcludes

      # Simple dnf install
      - name: neomutt

      # Just test part of git config
      - name: testservice
        desc: services and user space
        type: none
        config:
          - src: testservice/root_test.service
            dest: "/etc/systemd/system/root_test.service"
          - src: testservice/root_test.timer
            dest: "/etc/systemd/system/root_test.timer"
          - src: testservice/user_test.service
            dest: "~/.config/systemd/user/user_test.service"
          - src: testservice/root_test.timer
            dest: "~/.config/systemd/user/user_test.timer"
        services: ['root_test.timer']

  roles:
    - role: ws-dans
